const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let S={rows:[],heads:[],meta:{},cs:0,ce:100,ss:0,se:100};const base=s=>s.split('/')[0].trim(),fin=v=>Number.isFinite(+v),avg=(r,k)=>{let a=r.map(x=>+x[k]).filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null},time=ms=>{let s=ms/1000;return`${Math.floor(s/60)}:${(s%60).toFixed(1).padStart(4,'0')}`},fmt=v=>v==null?'--':(+v).toFixed(1);
function parse(t,n){let l=t.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean),h=l.findIndex(x=>/^Time[,;]/.test(x));if(h<0)throw Error('找不到 Time 欄位');let sep=l[h].includes(';')?';':',',heads=l[h].split(sep).map(base),rows=[];for(let i=h+1;i<l.length;i++){let a=l[i].split(sep);if(a.length<heads.length*.8)continue;let o={};heads.forEach((k,j)=>o[k]=fin(a[j])?+a[j]:a[j]);rows.push(o)}let meta={name:n};l.slice(0,h).forEach(x=>{let m=x.match(/^([^:]+):\s*(.+)$/);if(m)meta[m[1]]=m[2]});return{rows,heads,meta}}
function max(r,k){let a=r.map(x=>+x[k]).filter(Number.isFinite);return a.length?Math.max(...a):null}function min(r,k){let a=r.map(x=>+x[k]).filter(Number.isFinite);return a.length?Math.min(...a):null}function stat(a,b){return`<div class="stat"><small>${a}</small><b>${b}</b></div>`}function cut(a,b){let x=Math.floor(S.rows.length*a/100),y=Math.max(x+1,Math.ceil(S.rows.length*b/100));return S.rows.slice(x,y)}
function wot(r){let out=[],st=null,last=null,gap=null,on=x=>+x.TPS_Percent>=90&&+x.RPM>=4000;for(let i=0;i<r.length;i++){if(on(r[i])){if(st==null)st=i;last=i;gap=null}else if(st!=null){if(gap==null)gap=i;if(r[i].Time-r[gap].Time>300){push(st,last);st=last=gap=null}}}if(st!=null)push(st,last);function push(a,b){let q=r.slice(a,b+1),d=(r[b].Time-r[a].Time)/1000;if(d>=.5)out.push({a:r[a].Time,b:r[b].Time,d,rpm:max(q,'RPM'),speed:max(q,'Vehicle_Speed'),afr:avg(q,'AFR'),min:min(q,'AFR'),duty:max(q,'Cyl1_Injector_Period_Rate')})}return out}
function knocks(r){let out=[],st=null,last=null,on=x=>+x.KnockOccur>0||+x.KnockSARetard>0||+x.Knock_SA_Retard>0;for(let i=0;i<r.length;i++){if(on(r[i])){if(st==null)st=i;last=i}else if(st!=null){push(st,last);st=last=null}}if(st!=null)push(st,last);function push(a,b){let q=r.slice(a,b+1);out.push({a:r[a].Time,b:r[b].Time,d:(r[b].Time-r[a].Time)/1000,ret:Math.max(0,...q.flatMap(x=>[+x.KnockSARetard||0,+x.Knock_SA_Retard||0])),lev:max(q,'Knock_Level')||0,rpm:max(q,'RPM')})}return out}
function render(){let r=S.rows;$('#status').textContent=`${r.length.toLocaleString()} 筆資料`;$('#filename').textContent=S.meta.name;$('#overview').innerHTML='<div class="title">即時摘要</div><div class="grid">'+stat('最高 RPM',fmt(max(r,'RPM')))+stat('最高車速',fmt(max(r,'Vehicle_Speed'))+' km/h')+stat('最低 AFR',fmt(min(r,'AFR')))+stat('最高溫度',fmt(max(r,'T_Eng'))+'°C')+stat('最大 TPS',fmt(max(r,'TPS_Percent'))+'%')+stat('最大噴嘴率',fmt(max(r,'Cyl1_Injector_Period_Rate'))+'%')+'</div>';charts();analysis()}
let defs=[['RPM','RPM','#25d6c4'],['TPS / 車速','TPS_Percent,Vehicle_Speed','#ff9f43,#55aaff'],['AFR','AFR,iAF1_B_AFR','#ffd166,#ff5f6d'],['點火 / 溫度','SA,T_Eng','#b28dff,#ff5f6d']];function charts(){$('#chartList').innerHTML=defs.map((d,i)=>`<div class="card"><b>${d[0]}</b><div class="chart"><canvas data-k="${d[1]}" data-c="${d[2]}"></canvas></div></div>`).join('');drawAll()}function drawAll(){requestAnimationFrame(()=>$$('canvas').forEach(draw))}function draw(c){let r=cut(S.cs,S.ce),k=c.dataset.k.split(','),co=c.dataset.c.split(','),z=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=z.width*d;c.height=z.height*d;let x=c.getContext('2d');x.scale(d,d);let all=k.flatMap(q=>r.map(o=>+o[q]).filter(Number.isFinite));if(!all.length)return;let lo=Math.min(...all),hi=Math.max(...all);if(lo==hi){lo--;hi++}x.strokeStyle='#294252';for(let i=0;i<4;i++){let y=12+(z.height-35)*i/3;x.beginPath();x.moveTo(42,y);x.lineTo(z.width-8,y);x.stroke()}k.forEach((q,j)=>{x.strokeStyle=co[j];x.lineWidth=1.7;x.beginPath();r.forEach((o,i)=>{let xx=42+(z.width-50)*i/(r.length-1),yy=12+(z.height-35)*(hi-o[q])/(hi-lo);i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke()})}
function analysis(){let r=S.rows,W=wot(r),K=knocks(r);$('#wot').innerHTML=W.length?W.map((e,i)=>`<div class="event"><div class="head"><b>WOT #${i+1}</b><span>${time(e.a)}–${time(e.b)}</span></div><div class="meta"><span>${e.d.toFixed(1)} 秒</span><span>${fmt(e.rpm)} RPM</span><span>平均 AFR ${fmt(e.afr)}</span><span>最低 AFR ${fmt(e.min)}</span><span>車速 ${fmt(e.speed)}</span><span>噴嘴 ${fmt(e.duty)}%</span></div></div>`).join(''):'<div class="alert">無符合門檻的 WOT。</div>';let G=[['低負載',x=>+x.TPS_Percent<30],['中負載',x=>+x.TPS_Percent>=30&&+x.TPS_Percent<70],['高負載',x=>+x.TPS_Percent>=70]];$('#afr').innerHTML=G.map(([n,f])=>{let q=r.filter(x=>f(x)&&fin(x.AFR));return`<div class="event"><div class="head"><b>${n}</b><span>${q.length} 筆</span></div><div class="meta"><span>平均 ${fmt(avg(q,'AFR'))}</span><span>範圍 ${fmt(min(q,'AFR'))}–${fmt(max(q,'AFR'))}</span></div></div>`}).join('');$('#knock').innerHTML=K.length?K.map((e,i)=>`<div class="event"><div class="head"><b>事件 #${i+1}</b><span>${time(e.a)}–${time(e.b)}</span></div><div class="meta"><span>退角 ${fmt(e.ret)}°</span><span>等級 ${fmt(e.lev)}%</span><span>最高 ${fmt(e.rpm)} RPM</span></div></div>`).join(''):'<div class="alert">未偵測到爆震或退角欄位非零。</div>';sel()}
function sel(){let r=cut(S.ss,S.se);if(!r.length)return;$('#selTime').textContent=`${time(r[0].Time)} 至 ${time(r.at(-1).Time)}`;$('#selStats').innerHTML=stat('最高 RPM',fmt(max(r,'RPM')))+stat('平均 AFR',fmt(avg(r,'AFR')))+stat('平均 TPS',fmt(avg(r,'TPS_Percent'))+'%')+stat('平均點火',fmt(avg(r,'SA'))+'°')+stat('最高溫度',fmt(max(r,'T_Eng'))+'°C')+stat('最大噴嘴率',fmt(max(r,'Cyl1_Injector_Period_Rate'))+'%')}
$('#file').onchange=async e=>{try{Object.assign(S,parse(await e.target.files[0].text(),e.target.files[0].name));render()}catch(x){alert(x.message)}};$$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button,.view').forEach(x=>x.classList.remove('on'));b.classList.add('on');$('#'+b.dataset.v).classList.add('on');drawAll()});$('#chartStart').oninput=e=>{S.cs=Math.min(+e.target.value,S.ce-5);drawAll()};$('#chartEnd').oninput=e=>{S.ce=Math.max(+e.target.value,S.cs+5);drawAll()};$('#selStart').oninput=e=>{S.ss=Math.min(+e.target.value,S.se-5);sel()};$('#selEnd').oninput=e=>{S.se=Math.max(+e.target.value,S.ss+5);sel()};$('#pdf').onclick=()=>window.print();$('#csv').onclick=()=>{let r=cut(S.ss,S.se);if(!r.length)return alert('請先載入 Log');let k=S.heads,c=[k.join(','),...r.map(x=>k.map(y=>x[y]??'').join(','))].join('\n');download('\uFEFF'+c,'selection.csv','text/csv')};$('#json').onclick=()=>{if(!S.rows.length)return alert('請先載入 Log');download(JSON.stringify({file:S.meta.name,samples:S.rows.length,wot:wot(S.rows),knock:knocks(S.rows)},null,2),'analysis.json','application/json')};function download(t,n,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type}));a.download=n;a.click()}if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');

// v2.1 advanced analysis
let cursorRatio=0,AB={as:0,ae:50,bs:50,be:100};
function speedKey(){return S.heads.includes('PH_GPS_Speed')?'PH_GPS_Speed':S.heads.includes('Vehicle_Speed')?'Vehicle_Speed':S.heads.includes('GPS_Speed')?'GPS_Speed':null}
function accelerationRuns(rows){const k=speedKey();if(!k)return[];const runs=[];let armed=true,start=null;for(let i=1;i<rows.length;i++){const p=+rows[i-1][k],v=+rows[i][k];if(!fin(p)||!fin(v))continue;if(v<=5)armed=true;if(armed&&start===null&&p<=5&&v>5){start=i-1;armed=false}if(start!==null&&p<100&&v>=100){const t0=+rows[start].Time+(5-(+rows[start][k]))/Math.max(.001,(+rows[start+1][k]-+rows[start][k]))*(+rows[start+1].Time-+rows[start].Time);const t1=+rows[i-1].Time+(100-p)/Math.max(.001,v-p)*(+rows[i].Time-+rows[i-1].Time);if(t1>t0&&t1-t0<60000)runs.push({start:t0,end:t1,seconds:(t1-t0)/1000,key:k});start=null}if(start!==null&&(+rows[i].Time-+rows[start].Time)>60000)start=null}return runs}
function tuneReport(rows){const W=wot(rows),K=knocks(rows),high=rows.filter(x=>+x.TPS_Percent>=70&&fin(x.AFR)),duty=max(rows,'Cyl1_Injector_Period_Rate'),temp=max(rows,'T_Eng'),items=[];if(!W.length)items.push(['warn','WOT 資料不足','沒有符合 WOT 門檻的區段，無法評估高負載趨勢。']);else items.push(['','WOT 覆蓋',`偵測到 ${W.length} 個區段；請優先比較重複性高、條件相近的區段。`]);if(high.length)items.push(['','高負載 AFR',`平均 ${fmt(avg(high,'AFR'))}，範圍 ${fmt(min(high,'AFR'))}–${fmt(max(high,'AFR'))}。請依燃料、引擎規格與目標表確認，不自動給燃油增減百分比。`]);else items.push(['warn','AFR 資料不足','沒有可用的高負載 AFR 樣本。']);if(K.length)items.push(['bad','爆震／退角事件',`偵測到 ${K.length} 個事件，最大退角 ${fmt(Math.max(...K.map(x=>x.ret)))}°。建議先確認感知器、燃油品質、溫度與機械狀況，再由合格技師判讀。`]);else items.push(['','爆震欄位','未偵測到 KnockOccur 或退角欄位非零。']);if(duty!=null)items.push([duty>=90?'bad':duty>=80?'warn':'','噴嘴使用率',`最大 ${fmt(duty)}%。此值僅為紀錄摘要，需配合燃油壓力、噴嘴規格與 ECU 設定評估。`]);if(temp!=null)items.push(['','引擎溫度',`紀錄最高 ${fmt(temp)}°C，請與車種原廠規範及測試環境比較。`]);return items}
function reportRender(){if(!S.rows.length)return;$('#tuneReport').innerHTML=tuneReport(S.rows).map(x=>`<div class="reportitem ${x[0]}"><b>${x[1]}</b><div class="mut" style="margin-top:4px">${x[2]}</div></div>`).join('');const A=accelerationRuns(S.rows);$('#accel').innerHTML=A.length?A.map((x,i)=>`<div class="event"><div class="head"><b>0–100 #${i+1}</b><span>${x.seconds.toFixed(2)} 秒</span></div><div class="meta"><span>${time(x.start)}–${time(x.end)}</span><span>來源：${x.key}</span></div></div>`).join(''):`<div class="alert">沒有找到由 ≤5 km/h 起步並達到 100 km/h 的完整區段。結果會受速度來源、更新率與訊號品質影響。</div>`;compareRender()}
function metrics(r){return{rpm:max(r,'RPM'),afr:avg(r,'AFR'),tps:avg(r,'TPS_Percent'),sa:avg(r,'SA'),temp:max(r,'T_Eng'),duty:max(r,'Cyl1_Injector_Period_Rate')}}
function compareRender(){if(!S.rows.length)return;const A=metrics(cut(AB.as,AB.ae)),B=metrics(cut(AB.bs,AB.be)),rows=[['最高 RPM','rpm',''],['平均 AFR','afr',''],['平均 TPS','tps','%'],['平均點火','sa','°'],['最高溫度','temp','°C'],['最大噴嘴率','duty','%']];$('#compare').innerHTML='<div class="compare-row"><b>指標</b><b>A</b><b>B</b><b>B−A</b></div>'+rows.map(([n,k,u])=>{let d=A[k]!=null&&B[k]!=null?B[k]-A[k]:null;return`<div class="compare-row"><span>${n}</span><span>${fmt(A[k])}${u}</span><span>${fmt(B[k])}${u}</span><span>${d==null?'--':(d>=0?'+':'')+d.toFixed(1)+u}</span></div>`}).join('')}
function cursorMove(e,c){if(!S.rows.length)return;const rect=c.getBoundingClientRect(),clientX=e.touches?e.touches[0].clientX:e.clientX;cursorRatio=Math.max(0,Math.min(1,(clientX-rect.left)/rect.width));cursorRender()}
function cursorRender(){const r=cut(S.cs,S.ce);if(!r.length)return;const i=Math.min(r.length-1,Math.round(cursorRatio*(r.length-1))),o=r[i],keys=['Time','RPM','TPS_Percent','AFR','SA','T_Eng','Vehicle_Speed','PH_GPS_Speed','Cyl1_Injector_Period_Rate'].filter(k=>k==='Time'||S.heads.includes(k));$('#cursorValues').innerHTML=keys.map(k=>stat(k,k==='Time'?time(o[k]):fmt(o[k]))).join('');$$('canvas').forEach(c=>{c.parentElement.style.position='relative';let l=c.parentElement.querySelector('.cursorline');if(!l){l=document.createElement('i');l.className='cursorline';c.parentElement.appendChild(l)}l.style.left=(cursorRatio*100)+'%'})}
function bindAdvanced(){[['#aStart','as'],['#aEnd','ae'],['#bStart','bs'],['#bEnd','be']].forEach(([id,k])=>$(id).oninput=e=>{AB[k]=+e.target.value;if(AB.ae<AB.as+5)AB.ae=AB.as+5;if(AB.be<AB.bs+5)AB.be=AB.bs+5;compareRender()});$$('canvas').forEach(c=>{c.onpointerdown=e=>cursorMove(e,c);c.onpointermove=e=>{if(e.buttons)cursorMove(e,c)};c.ontouchmove=e=>cursorMove(e,c)});$('#sample').onclick=async()=>{try{let r=await fetch('sample.log');Object.assign(S,parse(await r.text(),'20261008_135603.log'));render()}catch{alert('請透過 HTTPS 或本機伺服器開啟範例。')}}}
const oldRender=render;render=function(){oldRender();setTimeout(()=>{bindAdvanced();cursorRender();reportRender()},0)};

// v2.2: 60-100 ranking and apply best run to synchronized charts
function speedRangeRuns(rows,low,high){
 const k=speedKey();if(!k)return[];const runs=[];let start=null;
 for(let i=1;i<rows.length;i++){
  const p=+rows[i-1][k],v=+rows[i][k];if(!fin(p)||!fin(v))continue;
  if(start===null&&p<low&&v>=low){const t=+rows[i-1].Time+(low-p)/Math.max(.001,v-p)*(+rows[i].Time-+rows[i-1].Time);start={index:i-1,time:t}}
  if(start!==null&&p<high&&v>=high){const end=+rows[i-1].Time+(high-p)/Math.max(.001,v-p)*(+rows[i].Time-+rows[i-1].Time),seconds=(end-start.time)/1000;if(seconds>0&&seconds<60){const segment=rows.slice(start.index,i+1);runs.push({start:start.time,end,seconds,key:k,startRPM:+segment[0].RPM||null,endRPM:+segment.at(-1).RPM||null,avgAFR:avg(segment,'AFR'),maxTPS:max(segment,'TPS_Percent')})}start=null}
  if(start!==null&&(v<low-10||+rows[i].Time-start.time>60000))start=null;
 }
 return runs.sort((a,b)=>a.seconds-b.seconds);
}
function timeToPercent(t){if(!S.rows.length)return 0;const first=+S.rows[0].Time,last=+S.rows.at(-1).Time;return Math.max(0,Math.min(100,(t-first)/(last-first)*100))}
function applyBestRun(run){
 const padMs=Math.max(300,(run.end-run.start)*.04);S.cs=timeToPercent(run.start-padMs);S.ce=timeToPercent(run.end+padMs);if(S.ce-S.cs<1){S.cs=Math.max(0,S.cs-.5);S.ce=Math.min(100,S.ce+.5)}
 $('#chartStart').value=S.cs;$('#chartEnd').value=S.ce;cursorRatio=Math.max(0,Math.min(1,(run.start-(+S.rows[0].Time+(+S.rows.at(-1).Time-+S.rows[0].Time)*S.cs/100))/((+S.rows.at(-1).Time-+S.rows[0].Time)*(S.ce-S.cs)/100)));
 $$('.nav button,.view').forEach(x=>x.classList.remove('on'));const tab=$('.nav button[data-v="charts"]');tab.classList.add('on');$('#charts').classList.add('on');drawAll();setTimeout(()=>{bindAdvanced();cursorRender();$('#cursorPanel').scrollIntoView({behavior:'smooth',block:'start'})},30)
}
function render60100(){
 const runs=speedRangeRuns(S.rows,60,100),root=$('#accel60100');if(!root)return;
 if(!runs.length){root.innerHTML='<div class="alert">沒有找到速度由 60 km/h 連續跨越至 100 km/h 的完整區段。</div>';return}
 root.innerHTML=runs.map((x,i)=>`<div class="event ${i===0?'bestbox':''}"><div class="head"><b>${i===0?'最佳 ':''}60–100 #${i+1}</b><span>${x.seconds.toFixed(2)} 秒</span></div><div class="meta"><span>${time(x.start)}–${time(x.end)}</span><span>來源：${x.key}</span><span>起始 RPM：${fmt(x.startRPM)}</span><span>結束 RPM：${fmt(x.endRPM)}</span><span>平均 AFR：${fmt(x.avgAFR)}</span><span>最大 TPS：${fmt(x.maxTPS)}%</span></div>${i===0?'<button class="btn applybest" id="applyBest60100">套用最佳區段到同步圖表</button>':''}</div>`).join('');
 $('#applyBest60100').onclick=()=>applyBestRun(runs[0]);
}
const priorReportRender=reportRender;reportRender=function(){priorReportRender();render60100()};

// v2.3 road-load power estimate. This is not a dynamometer measurement.
function smoothSeries(a,w=5){return a.map((_,i)=>{let s=0,n=0;for(let j=Math.max(0,i-w);j<=Math.min(a.length-1,i+w);j++){if(fin(a[j])){s+=+a[j];n++}}return n?s/n:null})}
function estimateRoadPower(rows,mass,crr,cda){
 const key=speedKey();if(!key||!mass)return[];
 const speed=smoothSeries(rows.map(x=>fin(x[key])?+x[key]/3.6:null),4),out=[],rho=1.225,g=9.80665;
 for(let i=2;i<rows.length-2;i++){
  if(speed[i-2]==null||speed[i+2]==null||!fin(rows[i].RPM))continue;
  const dt=(+rows[i+2].Time-+rows[i-2].Time)/1000;if(dt<=0)continue;
  const v=speed[i],a=(speed[i+2]-speed[i-2])/dt;
  if(v<5/3.6||a<=0)continue;
  const force=mass*a+mass*g*crr+0.5*rho*cda*v*v,powerW=force*v,rpm=+rows[i].RPM;
  if(powerW<0||powerW>1000000||rpm<500)continue;
  const hp=powerW/745.6998716,ps=powerW/735.49875,nm=powerW/(rpm*2*Math.PI/60);
  out.push({time:+rows[i].Time,rpm,speed:v*3.6,a,hp,ps,nm,key});
 }
 return out;
}
function renderPowerCurve(points){const root=$('#powerResults');if(!points.length){root.innerHTML='<div class="alert">沒有足夠的連續加速資料可估算。</div>';return}const peakHp=points.reduce((a,b)=>b.hp>a.hp?b:a),peakNm=points.reduce((a,b)=>b.nm>a.nm?b:a);root.innerHTML=`<div class="grid">${stat('估算最大輪上馬力',peakHp.hp.toFixed(1)+' hp')}${stat('估算公制馬力',peakHp.ps.toFixed(1)+' PS')}${stat('馬力峰值轉速',peakHp.rpm.toFixed(0)+' RPM')}${stat('估算最大等效扭力',peakNm.nm.toFixed(1)+' N·m')}${stat('扭力峰值轉速',peakNm.rpm.toFixed(0)+' RPM')}${stat('速度來源',peakHp.key)}</div><div class="alert warn" style="margin-top:10px">這是依總重量、速度變化、滾動阻力及空氣阻力推算的道路估值。坡度、風、速度誤差、取樣率、傳動損失與輸入參數都會顯著影響結果，不能當作引擎馬力機數據。</div><div class="powercurve"><canvas id="powerCanvas"></canvas></div>`;requestAnimationFrame(()=>drawPower(points))}
function drawPower(points){const c=$('#powerCanvas');if(!c)return;const z=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=z.width*d;c.height=z.height*d;const x=c.getContext('2d');x.scale(d,d);let p={l:42,r:8,t:12,b:22},lo=Math.min(...points.map(q=>q.rpm)),hi=Math.max(...points.map(q=>q.rpm)),hpMax=Math.max(...points.map(q=>q.hp)),nmMax=Math.max(...points.map(q=>q.nm));x.strokeStyle='#294252';for(let i=0;i<4;i++){let y=p.t+(z.height-p.t-p.b)*i/3;x.beginPath();x.moveTo(p.l,y);x.lineTo(z.width-p.r,y);x.stroke()}[[q=>q.hp,hpMax,'#25d6c4'],[q=>q.nm,nmMax,'#ff9f43']].forEach(([fn,m,col])=>{x.strokeStyle=col;x.lineWidth=1.6;x.beginPath();points.sort((a,b)=>a.rpm-b.rpm).forEach((q,i)=>{let xx=p.l+(z.width-p.l-p.r)*(q.rpm-lo)/Math.max(1,hi-lo),yy=p.t+(z.height-p.t-p.b)*(1-fn(q)/Math.max(1,m));i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke()});x.fillStyle='#8ca8ba';x.font='10px system-ui';x.fillText('hp',p.l,10);x.fillText('N·m',p.l+28,10);x.fillText(lo.toFixed(0)+' RPM',p.l,z.height-5);x.fillText(hi.toFixed(0),z.width-35,z.height-5)}
function bindPower(){const b=$('#calcPower');if(!b||b.dataset.bound)return;b.dataset.bound='1';const saved=localStorage.getItem('aracer-mass');if(saved)$('#vehicleMass').value=saved;b.onclick=()=>{if(!S.rows.length)return alert('請先載入 Log');const mass=+$('#vehicleMass').value,crr=+$('#crr').value,cda=+$('#cda').value;if(!mass||mass<50)return alert('請輸入包含騎士／駕駛的總重量');localStorage.setItem('aracer-mass',mass);renderPowerCurve(estimateRoadPower(S.rows,mass,crr,cda))}}
const renderV23=render;render=function(){renderV23();setTimeout(bindPower,0)};

// v2.4 settings
const DEFAULT_SETTINGS={wotTps:90,wotRpm:4000,wotDuration:.5,lowTps:30,highTps:70,launchSpeed:5,rememberMass:true};
let APP_SETTINGS={...DEFAULT_SETTINGS,...JSON.parse(localStorage.getItem('aracer-settings')||'{}')};
function fillSettings(){const m={setWotTps:'wotTps',setWotRpm:'wotRpm',setWotDuration:'wotDuration',setLowTps:'lowTps',setHighTps:'highTps',setLaunchSpeed:'launchSpeed'};Object.entries(m).forEach(([id,k])=>{const e=$('#'+id);if(e)e.value=APP_SETTINGS[k]});if($('#rememberMass'))$('#rememberMass').checked=APP_SETTINGS.rememberMass!==false}
function readSettings(){APP_SETTINGS={wotTps:+$('#setWotTps').value,wotRpm:+$('#setWotRpm').value,wotDuration:+$('#setWotDuration').value,lowTps:+$('#setLowTps').value,highTps:+$('#setHighTps').value,launchSpeed:+$('#setLaunchSpeed').value,rememberMass:$('#rememberMass').checked};if(APP_SETTINGS.lowTps>=APP_SETTINGS.highTps)throw Error('低負載上限必須小於高負載起點');localStorage.setItem('aracer-settings',JSON.stringify(APP_SETTINGS))}
function bindSettings(){fillSettings();$('#saveSettings').onclick=()=>{try{readSettings();if(S.rows.length)render();alert('設定已儲存並重新分析')}catch(e){alert(e.message)}};$('#resetSettings').onclick=()=>{APP_SETTINGS={...DEFAULT_SETTINGS};localStorage.setItem('aracer-settings',JSON.stringify(APP_SETTINGS));fillSettings();if(S.rows.length)render()};$('#clearSaved').onclick=()=>{localStorage.removeItem('aracer-settings');localStorage.removeItem('aracer-mass');APP_SETTINGS={...DEFAULT_SETTINGS};fillSettings();$('#vehicleMass')&&($('#vehicleMass').value='');alert('已清除已儲存設定')}}
// Replace analyzers with configurable variants used from v2.4 onward.
wot=function(r){let out=[],st=null,last=null,gap=null,on=x=>+x.TPS_Percent>=APP_SETTINGS.wotTps&&+x.RPM>=APP_SETTINGS.wotRpm;for(let i=0;i<r.length;i++){if(on(r[i])){if(st==null)st=i;last=i;gap=null}else if(st!=null){if(gap==null)gap=i;if(r[i].Time-r[gap].Time>300){push(st,last);st=last=gap=null}}}if(st!=null)push(st,last);function push(a,b){let q=r.slice(a,b+1),d=(r[b].Time-r[a].Time)/1000;if(d>=APP_SETTINGS.wotDuration)out.push({a:r[a].Time,b:r[b].Time,d,rpm:max(q,'RPM'),speed:max(q,'Vehicle_Speed'),afr:avg(q,'AFR'),min:min(q,'AFR'),duty:max(q,'Cyl1_Injector_Period_Rate')})}return out};
const renderV24=render;render=function(){renderV24();setTimeout(()=>{bindSettings();if(!APP_SETTINGS.rememberMass)localStorage.removeItem('aracer-mass')},0)};
setTimeout(bindSettings,0);

// v2.5 global iPhone-style Toast notifications
function showToast(type='success',message='',detail='',duration){
 const region=$('#toastRegion');if(!region)return;
 const kinds={success:{icon:'✓',ms:2200},warning:{icon:'!',ms:3400},error:{icon:'×',ms:4500}},kind=kinds[type]||kinds.success,ms=duration||kind.ms;
 const el=document.createElement('div');el.className=`toast ${type}`;el.setAttribute('role',type==='error'?'alert':'status');
 el.innerHTML=`<div class="toast-icon">${kind.icon}</div><div><div class="toast-message"></div>${detail?'<div class="toast-detail"></div>':''}</div><button class="toast-close" aria-label="關閉通知">×</button><div class="toast-progress"><i style="animation-duration:${ms}ms"></i></div>`;
 el.querySelector('.toast-message').textContent=message;if(detail)el.querySelector('.toast-detail').textContent=detail;
 const close=()=>{el.classList.remove('show');el.classList.add('hide');setTimeout(()=>el.remove(),260)};el.querySelector('.toast-close').onclick=close;
 region.appendChild(el);requestAnimationFrame(()=>el.classList.add('show'));setTimeout(close,ms);while(region.children.length>3)region.firstElementChild.remove();return el;
}
function toastError(e,fallback='操作失敗'){showToast('error',fallback,e?.message||String(e||''))}
// Replace blocking alerts globally so existing flows also use Toast.
window.alert=(message)=>{const text=String(message||'');const type=/錯誤|無法|找不到|不足|請先|不正確/.test(text)?'error':/警告|注意|未偵測/.test(text)?'warning':'success';showToast(type,text)};
// Toast-enhanced actions
const toastBaseRender=render;render=function(){toastBaseRender();setTimeout(()=>{showToast('success','Log 載入成功',`${S.rows.length.toLocaleString()} 筆資料 · WOT ${wot(S.rows).length} 段 · 爆震 ${knocks(S.rows).length} 次`)},20)};
const toastApplyBest=applyBestRun;applyBestRun=function(run){toastApplyBest(run);showToast('success','已套用最佳 60–100 區段',`${run.seconds.toFixed(2)} 秒 · 已切換至同步圖表`)};
const toastRenderPower=renderPowerCurve;renderPowerCurve=function(points){toastRenderPower(points);if(points.length){const ph=points.reduce((a,b)=>b.hp>a.hp?b:a),pt=points.reduce((a,b)=>b.nm>a.nm?b:a);showToast('success','馬力估算完成',`${ph.hp.toFixed(1)} hp · ${pt.nm.toFixed(1)} N·m`) }else showToast('warning','馬力估算資料不足','請確認重量與連續加速資料')};
// Rebind settings with non-blocking confirmations.
function bindToastSettings(){
 if(!$('#saveSettings')||$('#saveSettings').dataset.toastBound)return;$('#saveSettings').dataset.toastBound='1';
 $('#saveSettings').onclick=()=>{try{readSettings();if(S.rows.length)render();showToast('success','設定已儲存','已使用新參數重新分析')}catch(e){toastError(e,'設定未儲存')}};
 $('#resetSettings').onclick=()=>{APP_SETTINGS={...DEFAULT_SETTINGS};localStorage.setItem('aracer-settings',JSON.stringify(APP_SETTINGS));fillSettings();if(S.rows.length)render();showToast('success','已恢復預設值')};
 $('#clearSaved').onclick=()=>{localStorage.removeItem('aracer-settings');localStorage.removeItem('aracer-mass');APP_SETTINGS={...DEFAULT_SETTINGS};fillSettings();if($('#vehicleMass'))$('#vehicleMass').value='';showToast('success','已清除本機設定')};
}
setTimeout(bindToastSettings,0);
const toastBindSettings=bindSettings;bindSettings=function(){toastBindSettings();setTimeout(bindToastSettings,0)};

// v2.7 Unified Platform
const VEHICLE_PROFILES=[
 {id:'scooter',name:'通用速克達',desc:'日常使用的 CVT 速克達基準設定',weight:220,cda:.68,crr:.015,wotTps:90,wotRpm:5500,wotDuration:.5,lowTps:30,highTps:70,launchSpeed:5},
 {id:'sport_scooter',name:'運動速克達',desc:'偏高轉、較積極的速克達設定',weight:220,cda:.62,crr:.014,wotTps:92,wotRpm:6000,wotDuration:.4,lowTps:28,highTps:72,launchSpeed:5},
 {id:'motorcycle_na',name:'自然進氣檔車',desc:'一般自然進氣街車／仿賽',weight:250,cda:.5,crr:.014,wotTps:90,wotRpm:5000,wotDuration:.5,lowTps:25,highTps:70,launchSpeed:5},
 {id:'car_na',name:'自然進氣汽車',desc:'一般自然進氣乘用車',weight:1400,cda:.66,crr:.013,wotTps:88,wotRpm:3000,wotDuration:.7,lowTps:25,highTps:65,launchSpeed:5},
 {id:'custom',name:'自訂',desc:'保留目前手動參數'}
];
let currentProfile=localStorage.getItem('aracer-profile')||'scooter';
function stdev(r,k){const a=r.map(x=>+x[k]).filter(Number.isFinite);if(a.length<2)return null;const m=a.reduce((x,y)=>x+y,0)/a.length;return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length)}
function accelerationBand(rows,low,high){return speedRangeRuns(rows,low,high)}
function bestWot(rows){const list=wot(rows).map(e=>{const seg=rows.filter(x=>+x.Time>=e.a&&+x.Time<=e.b),afrSd=stdev(seg,'AFR')??9,tpsSd=stdev(seg,'TPS_Percent')??9,kn=knocks(seg).length;let score=100-Math.min(30,afrSd*15)-Math.min(20,tpsSd*2)-Math.min(40,kn*10);return{...e,score:Math.max(0,Math.round(score))}});return list.sort((a,b)=>b.score-a.score)}
function performanceScore(rows){const W=bestWot(rows),K=knocks(rows),high=rows.filter(x=>+x.TPS_Percent>=APP_SETTINGS.highTps&&fin(x.AFR)),afrSd=stdev(high,'AFR'),temp=max(rows,'T_Eng'),duty=max(rows,'Cyl1_Injector_Period_Rate');const afr=afrSd==null?50:Math.max(0,100-afrSd*25),kn=Math.max(0,100-K.length*12),ws=W.length?W[0].score:40,pow=duty==null?50:Math.max(0,100-Math.abs(75-Math.min(100,duty))*2),tp=temp==null?50:Math.max(0,100-Math.max(0,temp-90)*4);return{total:Math.round(afr*.25+kn*.25+ws*.20+pow*.15+tp*.15),parts:{afr:Math.round(afr),knock:Math.round(kn),wot:Math.round(ws),power:Math.round(pow),temp:Math.round(tp)}}}
function gradeFromScore(s){return s>=90?'A+':s>=80?'A':s>=70?'B':s>=60?'C':'D'}
function renderDashboard(){if(!S.rows.length)return;const p=performanceScore(S.rows),a60100=accelerationBand(S.rows,60,100),bw=bestWot(S.rows)[0],K=knocks(S.rows),mass=+$('#vehicleMass')?.value||+localStorage.getItem('aracer-mass')||null,power=mass?estimateRoadPower(S.rows,mass,+$('#crr')?.value||.015,+$('#cda')?.value||.68):[],peakHp=power.length?max(power,'hp'):null,peakNm=power.length?max(power,'nm'):null;$('#unifiedDashboard').innerHTML=`<div class="title">Unified Dashboard</div><div class="card"><div class="score-ring" style="--score:${p.total}"><b>${p.total}</b></div><div style="text-align:center;margin-top:8px"><span class="grade">${gradeFromScore(p.total)}</span><div class="mut">Performance Score</div></div></div><div class="dash-grid"><div class="dash-card"><small>最佳 60–100</small><b>${a60100.length?a60100[0].seconds.toFixed(2)+' s':'--'}</b></div><div class="dash-card"><small>最佳 WOT</small><b>${bw?bw.score+' / 100':'--'}</b></div><div class="dash-card"><small>估算峰值馬力</small><b>${peakHp?peakHp.toFixed(1)+' hp':'輸入重量'}</b></div><div class="dash-card"><small>估算峰值扭力</small><b>${peakNm?peakNm.toFixed(1)+' N·m':'輸入重量'}</b></div><div class="dash-card"><small>爆震事件</small><b>${K.length}</b></div><div class="dash-card"><small>車輛設定檔</small><b>${VEHICLE_PROFILES.find(x=>x.id===currentProfile)?.name||'自訂'}</b></div></div>`}
function runCard(label,runs){if(!runs.length)return`<div class="event"><div class="head"><b>${label}</b><span>無完整區段</span></div></div>`;const best=runs[0],av=runs.reduce((s,x)=>s+x.seconds,0)/runs.length,worst=runs.at(-1);return`<div class="event"><div class="head"><b>${label}</b><span>Best ${best.seconds.toFixed(2)} s</span></div><div class="meta"><span>Average ${av.toFixed(2)} s</span><span>Worst ${worst.seconds.toFixed(2)} s</span><span>${runs.length} runs</span><span>${best.key}</span></div><button class="btn run-btn" data-run-start="${best.start}" data-run-end="${best.end}" data-run-seconds="${best.seconds}">同步圖表重播最佳區段</button></div>`}
function renderUnifiedAnalysis(){if(!S.rows.length)return;const bands=[[0,60],[0,100],[40,80],[60,100],[80,120],[100,150]],runs=bands.map(x=>[`${x[0]}–${x[1]} km/h`,accelerationBand(S.rows,...x)]);$('#accelerationLab').innerHTML=runs.map(x=>runCard(...x)).join('');$$('[data-run-start]').forEach(b=>b.onclick=()=>applyBestRun({start:+b.dataset.runStart,end:+b.dataset.runEnd,seconds:+b.dataset.runSeconds}));const W=bestWot(S.rows);$('#smartWot').innerHTML=W.length?W.slice(0,5).map((e,i)=>`<div class="event"><div class="head"><b>${i===0?'最佳 ':''}WOT #${i+1}</b><span>${e.score}/100</span></div><div class="meta"><span>${time(e.a)}–${time(e.b)}</span><span>${e.d.toFixed(1)} s</span><span>${fmt(e.rpm)} RPM</span><span>AFR ${fmt(e.afr)}</span></div>${i===0?`<button class="btn run-btn" data-wot-a="${e.a}" data-wot-b="${e.b}">分析最佳 WOT</button>`:''}</div>`).join(''):'<div class="alert">無符合設定的 WOT。</div>';const wb=$('[data-wot-a]');if(wb)wb.onclick=()=>applyBestRun({start:+wb.dataset.wotA,end:+wb.dataset.wotB,seconds:(+wb.dataset.wotB-+wb.dataset.wotA)/1000});const groups=[['低負載',x=>+x.TPS_Percent<APP_SETTINGS.lowTps],['中負載',x=>+x.TPS_Percent>=APP_SETTINGS.lowTps&&+x.TPS_Percent<APP_SETTINGS.highTps],['高負載',x=>+x.TPS_Percent>=APP_SETTINGS.highTps]];$('#afrIntel').innerHTML=groups.map(([n,f])=>{const q=S.rows.filter(x=>f(x)&&fin(x.AFR)),sd=stdev(q,'AFR'),score=sd==null?0:Math.max(0,Math.round(100-sd*25));return`<div class="event"><div class="head"><b>${n}</b><span>穩定度 ${score}</span></div><div class="meta"><span>平均 ${fmt(avg(q,'AFR'))}</span><span>${fmt(min(q,'AFR'))}–${fmt(max(q,'AFR'))}</span><span>${q.length} 筆</span></div><div class="intel-meter"><i style="width:${score}%"></i></div></div>`}).join('');const K=knocks(S.rows),hot={};K.forEach(e=>{const bin=Math.floor((e.rpm||0)/1000)*1000;hot[bin]=(hot[bin]||0)+1});$('#knockIntel').innerHTML=`<div class="card"><div class="dash-grid">${stat('Knock Grade',gradeFromScore(Math.max(0,100-K.length*12)))}${stat('事件數',K.length)}${stat('最大退角',K.length?fmt(Math.max(...K.map(x=>x.ret)))+'°':'0.0°')}${stat('主要熱區',Object.keys(hot).length?Object.entries(hot).sort((a,b)=>b[1]-a[1])[0][0]+' RPM':'--')}</div></div>`;const p=performanceScore(S.rows);$('#performanceCenter').innerHTML=`<div class="card"><div class="score-ring" style="--score:${p.total}"><b>${p.total}</b></div><div class="dash-grid" style="margin-top:12px">${Object.entries(p.parts).map(([k,v])=>stat(k.toUpperCase(),v)).join('')}</div></div>`}
function normalizedRows(){const k=speedKey();return S.rows.map(x=>({time:x.Time,rpm:x.RPM,speed:k?x[k]:null,afr:x.AFR,tps:x.TPS_Percent,ignition:x.SA,engineTemp:x.T_Eng,injectorDuty:x.Cyl1_Injector_Period_Rate,knock:x.KnockOccur,knockRetard:Math.max(+x.KnockSARetard||0,+x.Knock_SA_Retard||0)}))}
function fullReport(){return{app:'aRacer Pro Unified',version:'2.7',generatedAt:new Date().toISOString(),file:S.meta.name,profile:VEHICLE_PROFILES.find(x=>x.id===currentProfile),settings:APP_SETTINGS,performance:performanceScore(S.rows),acceleration:{'0-60':accelerationBand(S.rows,0,60),'0-100':accelerationBand(S.rows,0,100),'40-80':accelerationBand(S.rows,40,80),'60-100':accelerationBand(S.rows,60,100),'80-120':accelerationBand(S.rows,80,120),'100-150':accelerationBand(S.rows,100,150)},wot:bestWot(S.rows),knock:knocks(S.rows)}}
function bindProfiles(){const sel=$('#profileSelect');if(!sel||sel.dataset.bound)return;sel.dataset.bound='1';sel.innerHTML=VEHICLE_PROFILES.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');sel.value=currentProfile;const desc=()=>$('#profileDescription').textContent=VEHICLE_PROFILES.find(x=>x.id===sel.value)?.desc||'';sel.onchange=desc;desc();$('#applyProfile').onclick=()=>{const p=VEHICLE_PROFILES.find(x=>x.id===sel.value);if(!p||p.id==='custom')return showToast('warning','自訂設定檔','請直接修改分析參數');currentProfile=p.id;localStorage.setItem('aracer-profile',p.id);APP_SETTINGS={...APP_SETTINGS,wotTps:p.wotTps,wotRpm:p.wotRpm,wotDuration:p.wotDuration,lowTps:p.lowTps,highTps:p.highTps,launchSpeed:p.launchSpeed};localStorage.setItem('aracer-settings',JSON.stringify(APP_SETTINGS));localStorage.setItem('aracer-mass',p.weight);fillSettings();if($('#vehicleMass'))$('#vehicleMass').value=p.weight;if($('#cda'))$('#cda').value=p.cda;if($('#crr'))$('#crr').value=p.crr;if(S.rows.length)render();showToast('success','已套用車輛設定檔',p.name)};$('#exportProfile').onclick=()=>download(JSON.stringify({profile:VEHICLE_PROFILES.find(x=>x.id===currentProfile),settings:APP_SETTINGS},null,2),'aracer-profile.json','application/json');$('#importProfile').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());APP_SETTINGS={...APP_SETTINGS,...(d.settings||d.profile||d)};currentProfile='custom';localStorage.setItem('aracer-settings',JSON.stringify(APP_SETTINGS));localStorage.setItem('aracer-profile','custom');fillSettings();if(S.rows.length)render();showToast('success','設定檔匯入成功')}catch(err){showToast('error','設定檔匯入失敗',err.message)}};$('#reportPdf').onclick=()=>window.print();$('#reportJson').onclick=()=>{if(!S.rows.length)return showToast('warning','請先載入 Log');download(JSON.stringify(fullReport(),null,2),'aracer-analysis-v27.json','application/json');showToast('success','完整分析 JSON 已匯出')};$('#reportCsv').onclick=()=>{if(!S.rows.length)return showToast('warning','請先載入 Log');const rows=normalizedRows(),keys=Object.keys(rows[0]),csv=[keys.join(','),...rows.map(x=>keys.map(k=>x[k]??'').join(','))].join('\n');download('\uFEFF'+csv,'aracer-normalized.csv','text/csv');showToast('success','正規化 CSV 已匯出')}}
const renderUnifiedBase=render;render=function(){renderUnifiedBase();setTimeout(()=>{renderDashboard();renderUnifiedAnalysis();bindProfiles()},0)};setTimeout(bindProfiles,0);
